#!/bin/bash
while [ -n "$1" ]; do
  case "$1" in 
    --make)
      catkin_make;
      source devel/setup.bash;;
    --install) 
      catkin_make install;
      source install/setup.bash;;
    --build) 
      catkin_make build;;
    --rebuild)
      rm -rf build;
      catkin_make build;;
  esac
  shift
done
