int32 client_key # client key that is asking for the request
int32 motor_count # how many motors I want
bool connect_or_disconnect # disconnecting or connecting to the server (true connect)
---
int32[] assigned_id # assigned motor to the client
int32 client_key  # client key that the request came in on
