// Generated by gencpp from file rover_msgs/DepthCamReading.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_DEPTHCAMREADING_H
#define ROVER_MSGS_MESSAGE_DEPTHCAMREADING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct DepthCamReading_
{
  typedef DepthCamReading_<ContainerAllocator> Type;

  DepthCamReading_()
    {
    }
  DepthCamReading_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rover_msgs::DepthCamReading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::DepthCamReading_<ContainerAllocator> const> ConstPtr;

}; // struct DepthCamReading_

typedef ::rover_msgs::DepthCamReading_<std::allocator<void> > DepthCamReading;

typedef boost::shared_ptr< ::rover_msgs::DepthCamReading > DepthCamReadingPtr;
typedef boost::shared_ptr< ::rover_msgs::DepthCamReading const> DepthCamReadingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::DepthCamReading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::DepthCamReading_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/joshashley/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/joshashley/Projects/LunaRover/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::DepthCamReading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::DepthCamReading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::DepthCamReading_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rover_msgs::DepthCamReading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/DepthCamReading";
  }

  static const char* value(const ::rover_msgs::DepthCamReading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# do not know what to put here\n"
;
  }

  static const char* value(const ::rover_msgs::DepthCamReading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthCamReading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::DepthCamReading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rover_msgs::DepthCamReading_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_DEPTHCAMREADING_H
