// Generated by gencpp from file rover_msgs/DigArmSetting.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_DIGARMSETTING_H
#define ROVER_MSGS_MESSAGE_DIGARMSETTING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct DigArmSetting_
{
  typedef DigArmSetting_<ContainerAllocator> Type;

  DigArmSetting_()
    : max_speed(0)
    , position(0)  {
    }
  DigArmSetting_(const ContainerAllocator& _alloc)
    : max_speed(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef int32_t _max_speed_type;
  _max_speed_type max_speed;

   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::rover_msgs::DigArmSetting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::DigArmSetting_<ContainerAllocator> const> ConstPtr;

}; // struct DigArmSetting_

typedef ::rover_msgs::DigArmSetting_<std::allocator<void> > DigArmSetting;

typedef boost::shared_ptr< ::rover_msgs::DigArmSetting > DigArmSettingPtr;
typedef boost::shared_ptr< ::rover_msgs::DigArmSetting const> DigArmSettingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::DigArmSetting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::DigArmSetting_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/joshashley/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/joshashley/Projects/LunaRover/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::DigArmSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::DigArmSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::DigArmSetting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "000b6f5563447cd704349a21ac608512";
  }

  static const char* value(const ::rover_msgs::DigArmSetting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x000b6f5563447cd7ULL;
  static const uint64_t static_value2 = 0x04349a21ac608512ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/DigArmSetting";
  }

  static const char* value(const ::rover_msgs::DigArmSetting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 max_speed # max speed for the actuator arm\n"
"int32 position # position we want it at\n"
;
  }

  static const char* value(const ::rover_msgs::DigArmSetting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_speed);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DigArmSetting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::DigArmSetting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::DigArmSetting_<ContainerAllocator>& v)
  {
    s << indent << "max_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_speed);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_DIGARMSETTING_H
