// Generated by gencpp from file rover_msgs/FWDSetting.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_FWDSETTING_H
#define ROVER_MSGS_MESSAGE_FWDSETTING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct FWDSetting_
{
  typedef FWDSetting_<ContainerAllocator> Type;

  FWDSetting_()
    : front_left(0)
    , front_right(0)
    , back_left(0)
    , back_right(0)  {
    }
  FWDSetting_(const ContainerAllocator& _alloc)
    : front_left(0)
    , front_right(0)
    , back_left(0)
    , back_right(0)  {
  (void)_alloc;
    }



   typedef int32_t _front_left_type;
  _front_left_type front_left;

   typedef int32_t _front_right_type;
  _front_right_type front_right;

   typedef int32_t _back_left_type;
  _back_left_type back_left;

   typedef int32_t _back_right_type;
  _back_right_type back_right;





  typedef boost::shared_ptr< ::rover_msgs::FWDSetting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::FWDSetting_<ContainerAllocator> const> ConstPtr;

}; // struct FWDSetting_

typedef ::rover_msgs::FWDSetting_<std::allocator<void> > FWDSetting;

typedef boost::shared_ptr< ::rover_msgs::FWDSetting > FWDSettingPtr;
typedef boost::shared_ptr< ::rover_msgs::FWDSetting const> FWDSettingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::FWDSetting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::FWDSetting_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/joshashley/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/joshashley/Projects/LunaRover/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::FWDSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::FWDSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::FWDSetting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::FWDSetting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::FWDSetting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::FWDSetting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::FWDSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68a4add6eda239765346c3ac2d3b82e1";
  }

  static const char* value(const ::rover_msgs::FWDSetting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68a4add6eda23976ULL;
  static const uint64_t static_value2 = 0x5346c3ac2d3b82e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::FWDSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/FWDSetting";
  }

  static const char* value(const ::rover_msgs::FWDSetting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::FWDSetting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 front_left  # front left \n"
"int32 front_right # front right\n"
"int32 back_left   # back left\n"
"int32 back_right  # back right\n"
;
  }

  static const char* value(const ::rover_msgs::FWDSetting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::FWDSetting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front_left);
      stream.next(m.front_right);
      stream.next(m.back_left);
      stream.next(m.back_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FWDSetting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::FWDSetting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::FWDSetting_<ContainerAllocator>& v)
  {
    s << indent << "front_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.front_left);
    s << indent << "front_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.front_right);
    s << indent << "back_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.back_left);
    s << indent << "back_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.back_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_FWDSETTING_H
