controller: "kora.luna_rover.controllers.test_cont.TestCont"
port1: "/dev/drv1"
port2: "/dev/drv2"
port3: "/dev/drv3"
port4: "/dev/drv4"
lin_max: 10   # max linear velocity in m/s
ang_max: 6.28 # max angular velocity in rads/s
