controller: "kora.luna_rover.controllers.teensy_4wd.Teensy4WD"
port: "/dev/ttyS0"
lin_max: 10   # max linear velocity in m/s
ang_max: 6.28 # max angular velocity in rads/s
governor_enabled: True # whether or not to listen to lidar ranges for motion limiting
